//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CRM.sp_dinamic
{
    using System;
    using System.Collections.Generic;
    
    public partial class ADMINISTRADOR
    {
        public string ADM_CODIGO { get; set; }
        public string ADM_NOMBRE { get; set; }
        public string ADM_PASSWORD { get; set; }
        public Nullable<System.DateTime> ADM_FECHA_CREACION { get; set; }
        public Nullable<System.DateTime> ADM_FECHA_ELIMINACION { get; set; }
        public string EMAIL { get; set; }
    }
}
