//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CRM.sp_dinamic
{
    using System;
    using System.Collections.Generic;
    
    public partial class CRM_Usuarios_Rol
    {
        public long ID { get; set; }
        public string codigoEmpresa { get; set; }
        public string alias { get; set; }
        public string nombreUser { get; set; }
        public string contrase { get; set; }
        public string email { get; set; }
        public string Rol { get; set; }
    }
}
