//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CRM.sp_dinamic
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class BDWENCOEntities : DbContext
    {
        public BDWENCOEntities()
            : base("name=BDWENCOEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<ADMINISTRADOR> ADMINISTRADOR { get; set; }
        public virtual DbSet<USUARIO_FAC> USUARIO_FAC { get; set; }
        public virtual DbSet<CRM_Usuarios_Rol> CRM_Usuarios_Rol { get; set; }
    
        public virtual ObjectResult<SP_EMPRESA_CLIENTE_CRM_Result> SP_EMPRESA_CLIENTE_CRM()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_EMPRESA_CLIENTE_CRM_Result>("SP_EMPRESA_CLIENTE_CRM");
        }
    
        public virtual ObjectResult<SP_EMPRESA_USUARIO_CRM_Result> SP_EMPRESA_USUARIO_CRM()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_EMPRESA_USUARIO_CRM_Result>("SP_EMPRESA_USUARIO_CRM");
        }
    
        public virtual ObjectResult<SP_ACTUALIZAR_USUARIO_R_Result> SP_ACTUALIZAR_USUARIO(string nOMBRE, string eMAIL, string eMPRESA, string aLIAS)
        {
            var nOMBREParameter = nOMBRE != null ?
                new ObjectParameter("NOMBRE", nOMBRE) :
                new ObjectParameter("NOMBRE", typeof(string));
    
            var eMAILParameter = eMAIL != null ?
                new ObjectParameter("EMAIL", eMAIL) :
                new ObjectParameter("EMAIL", typeof(string));
    
            var eMPRESAParameter = eMPRESA != null ?
                new ObjectParameter("EMPRESA", eMPRESA) :
                new ObjectParameter("EMPRESA", typeof(string));
    
            var aLIASParameter = aLIAS != null ?
                new ObjectParameter("ALIAS", aLIAS) :
                new ObjectParameter("ALIAS", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_ACTUALIZAR_USUARIO_R_Result>("SP_ACTUALIZAR_USUARIO", nOMBREParameter, eMAILParameter, eMPRESAParameter, aLIASParameter);
        }
    
        public virtual ObjectResult<SP_ACTUALIZAR_USUARIO_R_Result> SP_ACTUALIZAR_USAURIO_PASSWORD(string pASSWORD, string eMPRESA, string aLIAS)
        {
            var pASSWORDParameter = pASSWORD != null ?
                new ObjectParameter("PASSWORD", pASSWORD) :
                new ObjectParameter("PASSWORD", typeof(string));
    
            var eMPRESAParameter = eMPRESA != null ?
                new ObjectParameter("EMPRESA", eMPRESA) :
                new ObjectParameter("EMPRESA", typeof(string));
    
            var aLIASParameter = aLIAS != null ?
                new ObjectParameter("ALIAS", aLIAS) :
                new ObjectParameter("ALIAS", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_ACTUALIZAR_USUARIO_R_Result>("SP_ACTUALIZAR_USAURIO_PASSWORD", pASSWORDParameter, eMPRESAParameter, aLIASParameter);
        }
    
        public virtual ObjectResult<SP_PORTAL_VERIFICAR_DATABASE_Result> SP_PORTAL_VERIFICAR_DATABASE1(string bASEDATOS)
        {
            var bASEDATOSParameter = bASEDATOS != null ?
                new ObjectParameter("BASEDATOS", bASEDATOS) :
                new ObjectParameter("BASEDATOS", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_PORTAL_VERIFICAR_DATABASE_Result>("SP_PORTAL_VERIFICAR_DATABASE1", bASEDATOSParameter);
        }
    }
}
