//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CRM.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CONTACTO_VENTA
    {
        public string COD_CLIENTE { get; set; }
        public decimal COD_CONTACTO { get; set; }
        public string CONTACTO { get; set; }
        public string TELEFONO { get; set; }
        public string CORREO { get; set; }
        public string AREA { get; set; }
        public string CARGO { get; set; }
        public string CELULAR { get; set; }
    }
}
