//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CRM.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Entidades : DbContext
    {
        public Entidades()
            : base("name=Entidades")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<CONTACTO_POTENCIAL> CONTACTO_POTENCIAL { get; set; }
        public virtual DbSet<CONTACTO_VENTA> CONTACTO_VENTA { get; set; }
        public virtual DbSet<CRONOGRAMA> CRONOGRAMA { get; set; }
        public virtual DbSet<ESTADO_PROSPECTO> ESTADO_PROSPECTO { get; set; }
        public virtual DbSet<GRUPO_USUARIO> GRUPO_USUARIO { get; set; }
        public virtual DbSet<GRUPOS> GRUPOS { get; set; }
        public virtual DbSet<MAEART> MAEART { get; set; }
        public virtual DbSet<MAECLI> MAECLI { get; set; }
        public virtual DbSet<POTENCIALCLI> POTENCIALCLI { get; set; }
        public virtual DbSet<PRIORIDAD> PRIORIDAD { get; set; }
        public virtual DbSet<RESPONSABLES> RESPONSABLES { get; set; }
        public virtual DbSet<T_TIPO_CLIENTE> T_TIPO_CLIENTE { get; set; }
        public virtual DbSet<TIPO_ACTIVIDAD> TIPO_ACTIVIDAD { get; set; }
        public virtual DbSet<DIRE_CLIENTE> DIRE_CLIENTE { get; set; }
        public virtual DbSet<TIPO_MONEDA> TIPO_MONEDA { get; set; }
        public virtual DbSet<TABAYU> TABAYU { get; set; }
        public virtual DbSet<ESTATUS_PROSPECTO> ESTATUS_PROSPECTO { get; set; }
        public virtual DbSet<HISTORICO> HISTORICO { get; set; }
        public virtual DbSet<PROSPECTO> PROSPECTO { get; set; }
    }
}
