//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CRM.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class HISTORICO
    {
        public int id_historico { get; set; }
        public string descripcion { get; set; }
        public string titulo { get; set; }
        public System.DateTime fecha { get; set; }
        public Nullable<int> id_estatusOp { get; set; }
        public string id_usuario { get; set; }
        public Nullable<int> id_EstadoProspecto { get; set; }
        public string id_oportunidad { get; set; }
    
        public virtual PROSPECTO PROSPECTO { get; set; }
    }
}
