//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CRM.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MAEART
    {
        public string ACODIGO { get; set; }
        public string ACODIGO2 { get; set; }
        public string ADESCRI { get; set; }
        public string ADESCRI2 { get; set; }
        public string AFAMILIA { get; set; }
        public string AMODELO { get; set; }
        public string AUNIDAD { get; set; }
        public string AGRUPO { get; set; }
        public string ACUENTA { get; set; }
        public string AFSERIE { get; set; }
        public Nullable<decimal> APRECIO { get; set; }
        public Nullable<decimal> ADESCTO { get; set; }
        public Nullable<decimal> APRECOM { get; set; }
        public string ACODPRO { get; set; }
        public Nullable<System.DateTime> AFECHA { get; set; }
        public string ACASILLERO { get; set; }
        public string AFSTOCK { get; set; }
        public string AUSER { get; set; }
        public string AESTADO { get; set; }
        public Nullable<System.DateTime> AFECVEN { get; set; }
        public string ACODMON { get; set; }
        public string ATIPO { get; set; }
        public string ACOMENTA { get; set; }
        public string AFLOTE { get; set; }
        public string AFDECI { get; set; }
        public Nullable<decimal> AUNIART { get; set; }
        public Nullable<decimal> APESO { get; set; }
        public Nullable<decimal> AISCPOR { get; set; }
        public Nullable<decimal> AIGVPOR { get; set; }
        public Nullable<System.DateTime> AHORA { get; set; }
        public string AFPRELIB { get; set; }
        public string AFRESTA { get; set; }
        public string AFUNIREF { get; set; }
        public string AUNIREF { get; set; }
        public Nullable<decimal> AFACREF { get; set; }
        public Nullable<decimal> APDIS { get; set; }
        public Nullable<decimal> APCOM { get; set; }
        public string ACODMONC { get; set; }
        public bool AFLAGIGV { get; set; }
        public string ACOLOR { get; set; }
        public string AMARCA { get; set; }
        public string AFOTO { get; set; }
        public string ATALLA { get; set; }
        public Nullable<int> CODAUTO { get; set; }
        public string AFLAGPERC { get; set; }
        public string COD_IMAGEN { get; set; }
        public string UMREFERENCIA { get; set; }
        public string AMODELO1 { get; set; }
        public string AORIGEN { get; set; }
        public bool TERCERO { get; set; }
        public string MAR_CODIGO { get; set; }
        public string ZON_CODIGO { get; set; }
        public Nullable<System.DateTime> AULTFECCOMP { get; set; }
        public string AULTPROV { get; set; }
        public string AULTPAISPROV { get; set; }
        public string COD_ARANCEL { get; set; }
        public Nullable<double> APREFOB { get; set; }
        public Nullable<double> APRECIF { get; set; }
        public string AMONFOB { get; set; }
        public string AMONCIF { get; set; }
        public Nullable<bool> FLG_EXONERADO_IGV { get; set; }
        public string CODIGO_SUNAT { get; set; }
        public string COD_AUDITORIA { get; set; }
    }
}
