//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CRM.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PROSPECTO
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PROSPECTO()
        {
            this.CRONOGRAMA = new HashSet<CRONOGRAMA>();
            this.HISTORICO = new HashSet<HISTORICO>();
        }
    
        public string id_oportunidad { get; set; }
        public string nombre { get; set; }
        public Nullable<decimal> ingreso { get; set; }
        public Nullable<int> id_estadoOporunidad { get; set; }
        public string idCliente { get; set; }
        public Nullable<int> id_prioridad { get; set; }
        public string color { get; set; }
        public string id_usuario { get; set; }
        public string cierre_previsto { get; set; }
        public Nullable<int> id_categoria { get; set; }
        public string notas { get; set; }
        public Nullable<int> id_planificacion { get; set; }
        public Nullable<int> tipoCliente { get; set; }
        public string codigo_tipoMon { get; set; }
        public Nullable<int> porcentajeGanar { get; set; }
        public int id_estatusProspecto { get; set; }
        public Nullable<System.DateTime> fecha_inicial { get; set; }
        public Nullable<System.DateTime> fecha_final { get; set; }
        public Nullable<decimal> monto_logrado { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CRONOGRAMA> CRONOGRAMA { get; set; }
        public virtual ESTADO_PROSPECTO ESTADO_PROSPECTO { get; set; }
        public virtual ESTATUS_PROSPECTO ESTATUS_PROSPECTO { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HISTORICO> HISTORICO { get; set; }
        public virtual PRIORIDAD PRIORIDAD { get; set; }
        public virtual TIPO_MONEDA TIPO_MONEDA { get; set; }
    }
}
