//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CRM.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class RESPONSABLES
    {
        public int id_responsable { get; set; }
        public Nullable<int> id_actividad { get; set; }
        public Nullable<int> id_grupos { get; set; }
        public Nullable<int> id_usuario { get; set; }
    
        public virtual GRUPOS GRUPOS { get; set; }
    }
}
