//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CRM.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TABAYU
    {
        public string TCOD { get; set; }
        public string TCLAVE { get; set; }
        public string TDESCRI { get; set; }
        public string TDIAVEN { get; set; }
        public string TNIVEL { get; set; }
        public Nullable<System.DateTime> TDATE { get; set; }
        public string THORA { get; set; }
        public bool TRESTA { get; set; }
        public bool TADVALOR { get; set; }
        public bool TNOFOB { get; set; }
    }
}
